# Generated by Django 5.0.1 on 2024-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_text', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(null=True)),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
